// Compile web/schemas/*.json (dumped from the Rust type table by
// zensight-common/tests/web_schemas.rs) into src/types.gen.ts, so the
// browser's idea of a StreamDescriptor cannot drift from the sensor's.
//
//   node scripts/gen-types.mjs          # rewrite src/types.gen.ts
//   node scripts/gen-types.mjs --check  # fail if it would change (CI)
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");
const out = join(here, "..", "src", "types.gen.ts");
const check = process.argv.includes("--check");

const files = readdirSync(schemasDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

let body = `// GENERATED by scripts/gen-types.mjs from ../schemas/*.json — do not edit.
// The schemas are dumped from zensight-common's type table (the same documents
// every producer serves on @rpc/<producer>/describe) by
// zensight-common/tests/web_schemas.rs. Regenerate both with
//   UPDATE_WEB_SCHEMAS=1 cargo test -p zensight-common --test web_schemas
//   npm run gen
/* eslint-disable */
`;

for (const file of files) {
  const name = file.replace(/\.json$/, "");
  const schema = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  // schemars names the root after the Rust type (`Array_of_StreamDescriptor`,
  // `Command_for_StreamControl`); the file name is the identifier we want.
  delete schema.title;
  // A `$defs` entry without a `title` is inlined at its use site, which
  // loses `StreamControl` and `StreamEndReason` as names; the key IS the
  // Rust type name, so title it and it becomes an exported declaration.
  for (const [key, def] of Object.entries(schema.$defs ?? {})) {
    if (def && typeof def === "object" && !("title" in def)) def.title = key;
  }
  const ts = await compile(schema, name, {
    bannerComment: "",
    additionalProperties: false,
    // $defs are emitted once per file; the names are the Rust type names and
    // are shared across files, so each is declared once below.
    declareExternallyReferenced: true,
    style: { singleQuote: false, semi: true },
  });
  body += `\n// ── ${file} ${"─".repeat(Math.max(4, 60 - file.length))}\n${ts}`;
}

// Types referenced from several schemas (TierSpec, StreamControl, ...) come
// out once per file with identical bodies. TypeScript refuses duplicate
// interface *and* type-alias declarations across the same module, so keep the
// first occurrence of each top-level declaration.
const seen = new Set();
const kept = [];
let skipping = false;
for (const line of body.split("\n")) {
  const decl = /^export (?:interface|type) ([A-Za-z0-9_]+)\b/.exec(line);
  if (decl) {
    const name = decl[1];
    skipping = seen.has(name);
    seen.add(name);
  }
  if (!skipping) kept.push(line);
  // A declaration ends at the first blank line after it starts.
  if (skipping && line.trim() === "") skipping = false;
}
const rendered = kept.join("\n").replace(/\n{3,}/g, "\n\n");

if (check) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {
    /* missing counts as drift */
  }
  if (current !== rendered) {
    console.error(`${out} is out of date — run: npm run gen`);
    process.exit(1);
  }
  console.log("types.gen.ts is current");
} else {
  writeFileSync(out, rendered);
  console.log(`wrote ${out} from ${files.length} schema(s)`);
}
