//! The subject registry, compiled (RFC 08).
//!
//! Everything in this module is generated by `build.rs` from
//! `registry/*.toml`: per-producer `Subject` enums (typed constructors — an
//! unregistered subject does not construct), precedence-ordered parsers
//! (RFC 08 §1's parse direction), `ProcedureId` enums with `@rpc` key
//! builders, and each producer's raw registry slice (`REGISTRY_TOML`) for the
//! `introspect` procedure (RFC 08 §6).
//!
//! Lints (RFC 08 §5) run at build time; a violating registry file does not
//! compile.

include!(concat!(env!("OUT_DIR"), "/registry_gen.rs"));
