// GENERATED by scripts/gen-types.mjs from ../schemas/*.json — do not edit.
// The schemas are dumped from zensight-common's type table (the same documents
// every producer serves on @rpc/<producer>/describe) by
// zensight-common/tests/web_schemas.rs. Regenerate both with
//   UPDATE_WEB_SCHEMAS=1 cargo test -p zensight-common --test web_schemas
//   npm run gen
/* eslint-disable */

// ── StreamCommand.json ──────────────────────────────────────────
/**
 * The topic-specific command payload.
 */
export type StreamControl =
  | {
      /**
       * Requested codec (e.g. `h264`, `mjpeg` for the preview); `None` =
       * sensor default (video).
       */
      codec?: string | null;
      /**
       * Stream identifier (the `<stream>` key chunk).
       */
      stream: string;
      /**
       * Which tier to open (the `<tier>` key chunk); `None` = the sensor's
       * default tier. Ignored for the preview codec.
       */
      tier?: string | null;
      type: "open_stream";
    }
  | {
      /**
       * Codec, matching the open; `None` = video default.
       */
      codec?: string | null;
      /**
       * Stream identifier.
       */
      stream: string;
      /**
       * Tier, matching the open; `None` = default tier.
       */
      tier?: string | null;
      type: "close_stream";
    }
  | {
      /**
       * Stream identifier.
       */
      stream: string;
      /**
       * Which tier's encoder to force; `None` = default tier.
       */
      tier?: string | null;
      type: "request_keyframe";
    };

/**
 * Optional envelope carrying a correlation id alongside a command body.
 */
export interface StreamCommand {
  body: StreamControl;
  /**
   * Optional correlation id, echoed in a reply for request/response matching.
   */
  id?: string | null;
}

// ── StreamDescriptors.json ──────────────────────────────────────
export type StreamDescriptors = StreamDescriptor[];

/**
 * One advertised media stream, served from the `streams` query topic.
 *
 * **Capability-bearing** (#507): a viewer builds a sensible tier selector from
 * the camera's *native* geometry and the tiers on offer, without opening the
 * stream first. Native `width`/`height`/`fps` are probed from the source
 * (`None` when genuinely unknown — e.g. an RTSP stream whose SDP carries no
 * dimensions); `codecs` reflects the real per-source capability, not a
 * hardcoded pair.
 */
export interface StreamDescriptor {
  /**
   * Whether the stream is currently open (any tier publishing).
   */
  active: boolean;
  /**
   * Codecs this stream can be opened with (e.g. `["h264", "mjpeg"]`).
   */
  codecs: string[];
  /**
   * Optional human-readable description (camera position, …).
   */
  description?: string | null;
  /**
   * Native capture framerate; `None` if unknown.
   */
  fps?: number | null;
  /**
   * Native capture height in pixels; `None` if unknown.
   */
  height?: number | null;
  /**
   * Stream identifier (the `<stream>` key chunk).
   */
  stream: string;
  /**
   * The bandwidth tiers this stream offers, so a viewer can subscribe to an
   * exact `<tier>` key and never advertise a tier the camera can't feed.
   */
  tiers?: TierSpec[];
  /**
   * Native capture width in pixels; `None` if unknown.
   */
  width?: number | null;
}
/**
 * One named bandwidth **tier** a stream offers — the `<tier>` key chunk plus
 * its target encoder parameters (RFC 07 §1). Tiers are published concurrently,
 * each on its own `@media/<stream>/video/<codec>/<tier>` key; a viewer
 * subscribes to exactly the tier its link can take, so two viewers on
 * different links never fight over one encoder (#494, #497).
 *
 * This is the tier *definition* — the sensor owns the numbers; the wire and
 * the key carry the *name*. It appears in [`StreamDescriptor::tiers`] (the
 * catalogue); the ladder itself is configured in `configs/parallax.json5`.
 */
export interface TierSpec {
  /**
   * Target encoded bitrate.
   */
  bitrate_kbps: number;
  /**
   * Target framerate.
   */
  fps: number;
  /**
   * Aspect-preserving height cap in pixels; `None` = native.
   */
  max_height?: number | null;
  /**
   * Tier name — the `<tier>` key chunk (`low` / `medium` / `high`).
   */
  name: string;
}

// ── StreamStatus.json ───────────────────────────────────────────
/**
 * What happened.
 */
export type StreamEndReason =
  | {
      type: "closed";
    }
  | {
      type: "idle";
    }
  | {
      type: "superseded";
    }
  | {
      type: "shutdown";
    }
  | {
      type: "source_ended";
    }
  | {
      type: "stalled";
    }
  | {
      /**
       * The failure, **in the failing element's own words**. Never a
       * paraphrase: `node` and `message` stay separate on the wire, and only
       * [`Display`](std::fmt::Display) ever joins them.
       */
      message: string;
      /**
       * The element that failed, when the pipeline named one; `egress` when
       * the failure was on the producer's side of the sink (frame-metadata
       * encoding, or the media publish itself).
       */
      node?: string | null;
      type: "failed";
    }
  | {
      /**
       * Why the open failed, in the failing layer's own words.
       */
      message: string;
      type: "failed_open";
    };

/**
 * Current state of one stream, reported on the `stream/<stream>` status doc.
 *
 * **Per-tier** (#497): a stream can have several tiers live at once, each with
 * its own applied params and viewer count. A single `Option<profile>` could
 * not express two live tiers — this is a `Vec`.
 */
export interface StreamStatus {
  /**
   * Why the most recent tier of this stream stopped, if one has and the
   * stream has not since resumed on that tier (#691).
   *
   * **Absent means no tier has stopped since this stream last opened** — not
   * "stopped for an unknown reason". `skip_serializing_if` keeps it out of
   * the map entirely rather than present-and-null, the same discipline
   * [`FrameMeta`] and [`MediaReceiverReport`] follow.
   *
   * One end, not a per-tier history. This is an LWW state document (RFC 05
   * §5) republished on every transition, so it says what *is*; a consumer
   * that wants every end reads every transition, which every live consumer
   * already does.
   */
  last_end?: StreamEnd | null;
  /**
   * Whether the stream is currently open (any tier publishing).
   */
  open: boolean;
  /**
   * Stream identifier.
   */
  stream: string;
  /**
   * Per-tier state for every tier currently live.
   */
  tiers?: TierStatus[];
}
/**
 * Why one tier of a stream stopped, reported inside [`StreamStatus`] (#691).
 *
 * The tier is **named**, not implied. `StreamStatus::tiers` is a *live set* —
 * a tier that died is removed from it — so an end reported inside a
 * [`TierStatus`] would either be unreachable (the last tier's death empties
 * the vec entirely) or force a non-empty `tiers` onto an `open: false`
 * document, which every consumer reads as "these tiers are live". That would
 * be a worse lie than the one this type exists to end.
 */
export interface StreamEnd {
  reason: StreamEndReason;
  /**
   * Which tier ended: a ladder rung's name (`low`/`medium`/`high`), or the
   * literal `preview` for the JPEG preview profile.
   *
   * The same one-string tier vocabulary the `rx/{tier}/…` receiver-feedback
   * telemetry uses (#715), minted from the producer's own profile, so a
   * reported end can never name a tier an `open_stream` could not.
   */
  tier: string;
}
/**
 * State of one running tier, reported inside [`StreamStatus`].
 */
export interface TierStatus {
  applied: TierApplied;
  /**
   * Tier name (the `<tier>` key chunk).
   */
  tier: string;
  /**
   * Matching subscribers observed by this tier's media publisher.
   */
  viewers: number;
}
/**
 * Parameters actually in effect on this tier's encoder.
 */
export interface TierApplied {
  /**
   * Applied encoded bitrate.
   */
  bitrate_kbps: number;
  /**
   * Applied framerate cap.
   */
  fps: number;
  /**
   * Encoded height in pixels.
   */
  height: number;
  /**
   * Encoded width in pixels (post-scale, even-aligned).
   */
  width: number;
}
