// GENERATED by scripts/gen-types.mjs from ../schemas/*.json — do not edit.
// The schemas are dumped from zensight-common's type table (the same documents
// every producer serves on @rpc/<producer>/describe) by
// zensight-common/tests/web_schemas.rs. Regenerate both with
//   UPDATE_WEB_SCHEMAS=1 cargo test -p zensight-common --test web_schemas
//   npm run gen
/* eslint-disable */

// ── MediaReceiverReport.json ────────────────────────────────────
/**
 * Receiver feedback for one `@media` key — the payload of
 * `@rpc/<producer>/stream/report` (RFC 07 §1.1, #714).
 *
 * # What it is, and what a producer may do with it
 *
 * A **snapshot**, which is what makes the procedure's `idempotent = true`
 * true: every counter is cumulative since this consumer subscribed, so a
 * resend under RFC 05 retry repeats a statement rather than adding to one. A
 * delta payload would not be idempotent.
 *
 * RFC 07 §1.2 is **normative** about the other half: a producer **MUST NOT**
 * re-tune a shared tier from one consumer's report, and where it acts on
 * *aggregate* feedback it must state its arbitration rule — which must not be
 * "the most recent report". Two viewers share a tier; one reports loss; the
 * bitrate drops; the healthy viewer's picture degrades for a reason it cannot
 * see, caused by a peer it does not know exists. **Feedback informs; it does
 * not command.** The sanctioned adaptation is the *consumer* changing which
 * tier key it subscribes to, and the escape hatch for a viewer that needs its
 * own rate is a tier of its own.
 *
 * # Absent is not zero
 *
 * Four fields are `Option` because "not measured" and "measured as zero" are
 * different observations and a controller must be able to tell them apart.
 * The `skip_serializing_if` attributes are wire shape, not style: an absent
 * field is **missing from the map**, never present-and-null. RFC 07 §1.3 makes
 * this normative for frame age — where a deployment does not timestamp, frame
 * age is *not asked*, **never zero** — and the same reasoning covers a
 * consumer with no decode queue to report.
 *
 * Field order is pinned by `tests/receiver_report_corpus.rs`, since serde
 * emits fields in declaration order and the vectors are compared byte for
 * byte.
 */
export interface MediaReceiverReport {
  /**
   * Codec, as in [`StreamControl::CloseStream`]. `None` means the
   * producer's default video profile.
   *
   * Present because `(stream, tier)` alone cannot name the JPEG preview
   * key, and because reusing the open/close selector shape means a report
   * can never name a key an `OpenStream` could not.
   */
  codec?: string | null;
  /**
   * Stable for this viewer instance, regenerated when a tile reopens.
   *
   * **In the payload, never in a key** (RFC 07 §1.1). N viewers are N
   * callers of one key, told apart here — which is why the feedback surface
   * costs no keyspace at all, and why viewer-origin telemetry was rejected.
   */
  consumer_id: string;
  /**
   * Frames that reached the screen.
   */
  decoded_frames: number;
  /**
   * Decoder queue depth at the end of the interval.
   *
   * Absent when the consumer has no queue to report — the JPEG preview tile,
   * which decodes each frame as it arrives and has nothing to queue. `0`
   * would read "queue empty" where the truth is "no queue". The H.264 tile
   * does report one (#717): a bounded channel drained by the decode task, so
   * the depth is `max_capacity() - capacity()` — the browser tile's
   * `decodeQueueSize`, same field and same meaning.
   */
  decoder_queue_depth?: number | null;
  /**
   * Frames the consumer shed on purpose (a deadline miss, a resync).
   */
  dropped_frames: number;
  /**
   * **Maximum** frame age over the interval, same clock and same caveats.
   *
   * Both a median and a max, because a producer aggregating N consumers must
   * publish both a worst case and a typical case, and one scalar per
   * consumer can feed only one of them honestly.
   */
  frame_age_max_ms?: number | null;
  /**
   * **Median** frame age over the interval: publisher HLC minus local
   * arrival, in milliseconds.
   *
   * *Observed skewed latency* in RFC 07 §1.3's sense — an observation, never
   * a verdict on the transport. **Negative values are reported, not
   * clamped**, because a negative age *is* the skew evidence. Absent when
   * the samples arrived unstamped: that is "not asked", and treating it as
   * zero silently disables every deadline built on it.
   */
  frame_age_ms?: number | null;
  /**
   * Inter-arrival jitter, milliseconds. Undefined before the second frame.
   */
  interarrival_jitter_ms?: number | null;
  /**
   * Milliseconds covered by this report.
   *
   * A **duration**, deliberately, where a wallclock instant would have been
   * the obvious choice. A consumer's wallclock is a second skewed cross-host
   * clock, and its only plausible use — `now - report_ms` — is precisely the
   * laundered-latency mistake RFC 07 §1.3 forbids. The producer already
   * knows when the report arrived; what it cannot know is the window the
   * counters cover, which is what turns them into rates.
   */
  interval_ms: number;
  /**
   * Sequence number of the last keyframe the consumer decoded.
   */
  last_keyframe_sequence?: number | null;
  /**
   * The highest `FrameMeta.sequence` seen.
   */
  last_sequence: number;
  /**
   * Frames inferred missing from sequence gaps — *network* loss.
   */
  lost_frames: number;
  /**
   * Samples received on this key.
   */
  received_frames: number;
  /**
   * Consumer-local milliseconds elapsed since that keyframe.
   *
   * Monotonic elapsed time on one host, not a cross-host subtraction: it can
   * never be negative, and it must not share a mental bucket with
   * [`Self::frame_age_ms`], which can. Hence the name.
   */
  since_last_keyframe_ms?: number | null;
  /**
   * Stream identifier.
   */
  stream: string;
  /**
   * Tier name. `None` means the producer's default tier, as in
   * [`StreamControl::OpenStream`].
   */
  tier?: string | null;
}

// ── StreamCommand.json ──────────────────────────────────────────
/**
 * The topic-specific command payload.
 */
export type StreamControl =
  | {
      /**
       * Requested codec (e.g. `h264`, `mjpeg` for the preview); `None` =
       * sensor default (video).
       */
      codec?: string | null;
      /**
       * Stream identifier (the `<stream>` key chunk).
       */
      stream: string;
      /**
       * Which tier to open (the `<tier>` key chunk); `None` = the sensor's
       * default tier. Ignored for the preview codec.
       */
      tier?: string | null;
      type: "open_stream";
    }
  | {
      /**
       * Codec, matching the open; `None` = video default.
       */
      codec?: string | null;
      /**
       * Stream identifier.
       */
      stream: string;
      /**
       * Tier, matching the open; `None` = default tier.
       */
      tier?: string | null;
      type: "close_stream";
    }
  | {
      /**
       * Stream identifier.
       */
      stream: string;
      /**
       * Which tier's encoder to force; `None` = default tier.
       */
      tier?: string | null;
      type: "request_keyframe";
    };

/**
 * Optional envelope carrying a correlation id alongside a command body.
 */
export interface StreamCommand {
  body: StreamControl;
  /**
   * Optional correlation id, echoed in a reply for request/response matching.
   */
  id?: string | null;
}

// ── StreamDescriptors.json ──────────────────────────────────────
export type StreamDescriptors = StreamDescriptor[];

/**
 * One advertised media stream, served from the `streams` query topic.
 *
 * **Capability-bearing** (#507): a viewer builds a sensible tier selector from
 * the camera's *native* geometry and the tiers on offer, without opening the
 * stream first. Native `width`/`height`/`fps` are probed from the source
 * (`None` when genuinely unknown — e.g. an RTSP stream whose SDP carries no
 * dimensions); `codecs` reflects the real per-source capability, not a
 * hardcoded pair.
 */
export interface StreamDescriptor {
  /**
   * Whether the stream is currently open (any tier publishing).
   */
  active: boolean;
  /**
   * Codecs this stream can be opened with (e.g. `["h264", "mjpeg"]`).
   */
  codecs: string[];
  /**
   * Optional human-readable description (camera position, …).
   */
  description?: string | null;
  /**
   * Native capture framerate; `None` if unknown.
   */
  fps?: number | null;
  /**
   * Native capture height in pixels; `None` if unknown.
   */
  height?: number | null;
  /**
   * Stream identifier (the `<stream>` key chunk).
   */
  stream: string;
  /**
   * The bandwidth tiers this stream offers, so a viewer can subscribe to an
   * exact `<tier>` key and never advertise a tier the camera can't feed.
   */
  tiers?: TierSpec[];
  /**
   * Native capture width in pixels; `None` if unknown.
   */
  width?: number | null;
}
/**
 * One named bandwidth **tier** a stream offers — the `<tier>` key chunk plus
 * its target encoder parameters (RFC 07 §1). Tiers are published concurrently,
 * each on its own `@media/<stream>/video/<codec>/<tier>` key; a viewer
 * subscribes to exactly the tier its link can take, so two viewers on
 * different links never fight over one encoder (#494, #497).
 *
 * This is the tier *definition* — the sensor owns the numbers; the wire and
 * the key carry the *name*. It appears in [`StreamDescriptor::tiers`] (the
 * catalogue); the ladder itself is configured in `configs/parallax.json5`.
 */
export interface TierSpec {
  /**
   * Target encoded bitrate.
   */
  bitrate_kbps: number;
  /**
   * Target framerate.
   */
  fps: number;
  /**
   * Aspect-preserving height cap in pixels; `None` = native.
   */
  max_height?: number | null;
  /**
   * Tier name — the `<tier>` key chunk (`low` / `medium` / `high`).
   */
  name: string;
}

// ── StreamStatus.json ───────────────────────────────────────────
/**
 * What happened.
 */
export type StreamEndReason =
  | {
      type: "closed";
    }
  | {
      type: "idle";
    }
  | {
      type: "superseded";
    }
  | {
      type: "shutdown";
    }
  | {
      type: "source_ended";
    }
  | {
      type: "stalled";
    }
  | {
      /**
       * The failure, **in the failing element's own words**. Never a
       * paraphrase: `node` and `message` stay separate on the wire, and only
       * [`Display`](std::fmt::Display) ever joins them.
       */
      message: string;
      /**
       * The element that failed, when the pipeline named one; `egress` when
       * the failure was on the producer's side of the sink (frame-metadata
       * encoding, or the media publish itself).
       */
      node?: string | null;
      type: "failed";
    }
  | {
      /**
       * Why the open failed, in the failing layer's own words.
       */
      message: string;
      type: "failed_open";
    };

/**
 * Current state of one stream, reported on the `stream/<stream>` status doc.
 *
 * **Per-tier** (#497): a stream can have several tiers live at once, each with
 * its own applied params and viewer count. A single `Option<profile>` could
 * not express two live tiers — this is a `Vec`.
 */
export interface StreamStatus {
  /**
   * Why the most recent tier of this stream stopped, if one has and the
   * stream has not since resumed on that tier (#691).
   *
   * **Absent means no tier has stopped since this stream last opened** — not
   * "stopped for an unknown reason". `skip_serializing_if` keeps it out of
   * the map entirely rather than present-and-null, the same discipline
   * [`FrameMeta`] and [`MediaReceiverReport`] follow.
   *
   * One end, not a per-tier history. This is an LWW state document (RFC 05
   * §5) republished on every transition, so it says what *is*; a consumer
   * that wants every end reads every transition, which every live consumer
   * already does.
   */
  last_end?: StreamEnd | null;
  /**
   * Whether the stream is currently open (any tier publishing).
   */
  open: boolean;
  /**
   * Stream identifier.
   */
  stream: string;
  /**
   * Per-tier state for every tier currently live.
   */
  tiers?: TierStatus[];
}
/**
 * Why one tier of a stream stopped, reported inside [`StreamStatus`] (#691).
 *
 * The tier is **named**, not implied. `StreamStatus::tiers` is a *live set* —
 * a tier that died is removed from it — so an end reported inside a
 * [`TierStatus`] would either be unreachable (the last tier's death empties
 * the vec entirely) or force a non-empty `tiers` onto an `open: false`
 * document, which every consumer reads as "these tiers are live". That would
 * be a worse lie than the one this type exists to end.
 */
export interface StreamEnd {
  reason: StreamEndReason;
  /**
   * Which tier ended: a ladder rung's name (`low`/`medium`/`high`), or the
   * literal `preview` for the JPEG preview profile.
   *
   * The same one-string tier vocabulary the `rx/{tier}/…` receiver-feedback
   * telemetry uses (#715), minted from the producer's own profile, so a
   * reported end can never name a tier an `open_stream` could not.
   */
  tier: string;
}
/**
 * State of one running tier, reported inside [`StreamStatus`].
 */
export interface TierStatus {
  applied: TierApplied;
  /**
   * Tier name (the `<tier>` key chunk).
   */
  tier: string;
  /**
   * Matching subscribers observed by this tier's media publisher.
   */
  viewers: number;
}
/**
 * Parameters actually in effect on this tier's encoder.
 */
export interface TierApplied {
  /**
   * Applied encoded bitrate.
   */
  bitrate_kbps: number;
  /**
   * Applied framerate cap.
   */
  fps: number;
  /**
   * Encoded height in pixels.
   */
  height: number;
  /**
   * Encoded width in pixels (post-scale, even-aligned).
   */
  width: number;
}
